[start]
cmd = "bash start-railway.sh"

[variables]
PHP_VERSION = "8.2"

[phases.setup]
cmds = [
    "mkdir -p storage/framework/{cache,sessions,views}",
    "mkdir -p storage/logs",
    "chmod -R 775 storage bootstrap/cache"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]
